export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const ASSETS_FETCHING = "ASSETS_FETCHING";
export const ASSETS_FETCH_ERROR = "ASSETS_FETCH_ERROR";
export const ASSETS_FETCH_SUCCESS = "ASSETS_FETCH_SUCCESS";

export default {
  LOGIN_USER,
  LOGOUT_USER,
  ASSETS_FETCHING,
  ASSETS_FETCH_ERROR,
  ASSETS_FETCH_SUCCESS
};
