export const CLIENT_ID = "CLIENT_ID";
export const CLIENT_SECRET = "CLIENT_SECRET";
export const SUCCESS_URI = "SUCCESS_URI";
export const AUTHORIZATION_CODE = "AUTHORIZATION_CODE";

export default {
  CLIENT_ID,
  CLIENT_SECRET,
  SUCCESS_URI,
  AUTHORIZATION_CODE
};
